--- 
engines:
  csslint: 
    enabled: true
  duplication: 
    config: 
      languages: 
        - javascript
    enabled: true
    checks:
      Similar code:
        enabled: false
  eslint: 
    enabled: true
  golint: 
    enabled: true
  fixme:
    enabled: true      
  git-legal:
    enabled: true  
  rubocop: 
    enabled: true
exclude_paths: 
  - build/**/*
  - doc/**/*
  - examples/**/*
  - external/**/*
  - licenses-3rd/**/*
  - shaders/**/*
  - tests/**/*
  - tutorials/**/*
  - src/Layer/JsVotable/**/*
  - src/Layer/JsCSV/**/*
  - src/Renderer/glMatrix.js
  - src/Renderer/pnltri.js
  - src/SceneGraph/**/*
  - src/Renderer/pnltri.min.js  
  - Mizar.min.js
  - "**.png"
  - "**.jpg"
  - "**.jpeg"
ratings: 
  paths: 
    - src/**
